//
// Tunnel, with fog
//
// texturetunnel's polar lookup, darkened toward the vanishing point. Fog on
// an indexed photo can't be a straight multiply the way it is on a
// generated byte texture: the photo's bytes are palette indices, and
// scaling an index jumps to an unrelated color, not a darker one. So each
// shade is a separate lookup instead: FogTable[index * SHADES + shade]
// holds, for every one of the photo's colors, the nearest palette entry to
// that color scaled toward black, built once by RETRO_CreatePaletteShadeTable.
// The photo leaves no palette entry spare for a clean black ramp of its
// own, so the darkest shade lands on whichever dark colors the photo
// happens to hold rather than true black.
//
// ShadeTable shares the wandering-origin indexing the angle and depth
// tables use, but unlike them is never wrapped: r grows outward from the
// vanishing point without folding back, so the shade climbs once from
// black at the mouth to full color at the rim instead of cycling.
//
// Author: Johan Gardhage <johan.gardhage@gmail.com>
//
#include "lib/retro.h"
#include "lib/retromain.h"
#include "lib/retroshadetable.h"

#define TEXTURE_WIDTH 256
#define TEXTURE_HEIGHT 256
#define TUNNEL_RATIO (32 * TEXTURE_HEIGHT) // v = RATIO/r, so 32 texture rows per 1/r
#define TUNNEL_SPEED 1.0 // seconds of flight per second
#define TUNNEL_SPIN 0.25 // texture turns around the axis per second of flight
#define TUNNEL_WOBBLE (33.0 / 10.0) // nod/sway; with 2π this is a 20π period
#define TUNNEL_PERIOD (20 * M_PI)
#define TUNNEL_FOG_SHADES 32 // steps from black to full color
#define TUNNEL_FOG_RADIUS (RETRO_WIDTH * 0.6) // screen-space radius fog climbs across

int DepthTable[2 * RETRO_HEIGHT][2 * RETRO_WIDTH];
int AngleTable[2 * RETRO_HEIGHT][2 * RETRO_WIDTH];
unsigned char ShadeTable[2 * RETRO_HEIGHT][2 * RETRO_WIDTH];
unsigned char FogTable[RETRO_COLORS * TUNNEL_FOG_SHADES];

void DEMO_Render(double time, double deltatime)
{
	// Calculate phase
	double phase = fmod(time * TUNNEL_SPEED, TUNNEL_PERIOD);

	unsigned char *image = RETRO_ImageData();

	// Calculate tunnel movement
	int sx = TEXTURE_WIDTH * phase;
	int sy = TEXTURE_HEIGHT * TUNNEL_SPIN * phase;

	// Calculate camera movement
	int dx = RETRO_WIDTH / 2.0 + RETRO_WIDTH / 2.0 * cos(phase);
	int dy = RETRO_HEIGHT / 2.0 + RETRO_HEIGHT / 2.0 * sin(phase * TUNNEL_WOBBLE);

	// Draw tunnel
	for (int y = 0; y < RETRO_HEIGHT; y++) {
		for (int x = 0; x < RETRO_WIDTH; x++) {
			int tx = WRAP(DepthTable[y + dy][x + dx] + sx, TEXTURE_WIDTH);
			int ty = WRAP(AngleTable[y + dy][x + dx] + sy, TEXTURE_HEIGHT);
			unsigned char shade = ShadeTable[y + dy][x + dx];
			unsigned char color = image[ty * TEXTURE_WIDTH + tx];

			RETRO_PutPixel(x, y, FogTable[color * TUNNEL_FOG_SHADES + shade]);
		}
	}
}

void DEMO_Initialize(void)
{
	RETRO_Image *picture = RETRO_LoadImage("assets/flowers_256x256.pcx", true);

	RETRO_CreatePaletteShadeTable(picture->palette, RETRO_COLORS, TUNNEL_FOG_SHADES, FogTable);

	// Init tables
	for (int y = 0; y < RETRO_HEIGHT * 2; y++) {
		for (int x = 0; x < RETRO_WIDTH * 2; x++) {
			int dx = x - RETRO_WIDTH;
			int dy = y - RETRO_HEIGHT;
			double r = sqrt((double)dx * dx + (double)dy * dy);

			AngleTable[y][x] = atan2(dx, dy) * TEXTURE_WIDTH / M_PI;
			DepthTable[y][x] = TUNNEL_RATIO / MAX(1.0, r);
			ShadeTable[y][x] = CLAMP(r / TUNNEL_FOG_RADIUS * TUNNEL_FOG_SHADES, 0, TUNNEL_FOG_SHADES);
		}
	}
}
